### ISSUE TITLE
no Connect to Notification

### ISSUE THREAD

**Issue by reddexx** [log-forge/logforge#8]
```yml
version: "3.9"

services:
  logforge-backend:
    image: madanb13/logforge-backend:latest
    container_name: ${BACKEND_SERVICE_CONTAINER_NAME:-logforge-backend}
    environment:
      PORT: "${BACKEND_SERVICE_PORT:-9101}" # Edit to 9101
      NOTIFIER_SERVICE_CONTAINER_NAME: "${NOTIFIER_SERVICE_CONTAINER_NAME:-logforge-notifier}"
      NOTIFIER_PLAIN_PORT: "${NOTIFIER_PLAIN_PORT:-9103}" # Edit to 9103
    networks:
      - logforge-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "${EXPOSED_BACKEND_PORT:-9100}:${BACKEND_SERVICE_PORT:-9101}" # Edit to 9100:9101
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  logforge-frontend:
    image: madanb13/logforge-frontend:latest
    container_name: ${FRONTEND_SERVICE_CONTAINER_NAME:-logforge-frontend}
    environment:
      VITE_BACKEND_SERVICE_HOST: "http://${BACKEND_SERVICE_CONTAINER_NAME:-logforge-backend}"
      VITE_BACKEND_SERVICE_PORT: "${BACKEND_SERVICE_PORT:-9101}" # Edit to 9101
      VITE_EXPOSED_BACKEND_PORT: "${EXPOSED_BACKEND_PORT:-9100}" # Edit to 9100
      VITE_NOTIFIER_PORT: "${NOTIFIER_WEB_PORT:-9105}" # Edit to 9105
    ports:
      - "${EXPOSED_FRONTEND_PORT:-3000}:${FRONTEND_SERVICE_PORT:-3000}"
    networks:
      - logforge-network
    depends_on:
      - logforge-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  logforge-notifier:
    image: madanb13/logforge-notifier:latest
    container_name: ${NOTIFIER_SERVICE_CONTAINER_NAME:-logforge-notifier}
    ports:
      - "${NOTIFIER_PLAIN_PORT:-9103}:9103" # Edit to 9103:9103
      - "${NOTIFIER_WEB_PORT:-9105}:9105" # Edit to 9105:9105
    volumes:
      - logforge_notifier_data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - logforge-network
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  logforge-autoupdate:
    image: madanb13/logforge-autoupdate:latest
    container_name: ${AUTOUPDATE_SERVICE_NAME:-logforge-autoupdate}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  logforge-network:
    driver: bridge

volumes:
  logforge_notifier_data:
```

![Image](https://github.com/user-attachments/assets/b0f6d343-2426-4e17-ba7f-b140969c7c7e)

I have a Custom Compose from Vanilla Version, as the ports were all already occupied.
Can't the 4 containers simply be unified into one image?

**Comment by reddexx** [comment]
i found this problem.
My Port - Mapping is Wrong

i correct this :D

**Comment by reddexx** [comment]
```yml
version: "3.9"

services:
  logforge-backend:
    image: madanb13/logforge-backend:latest
    container_name: ${BACKEND_SERVICE_CONTAINER_NAME:-logforge-backend}
    environment:
      PORT: "${BACKEND_SERVICE_PORT:-9101}" # Geändert zu 9101
      NOTIFIER_SERVICE_CONTAINER_NAME: "${NOTIFIER_SERVICE_CONTAINER_NAME:-logforge-notifier}"
      NOTIFIER_PLAIN_PORT: "${NOTIFIER_PLAIN_PORT:-9103}" # Geändert zu 9103
    networks:
      - logforge-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "${EXPOSED_BACKEND_PORT:-9100}:${BACKEND_SERVICE_PORT:-9101}" # Geändert zu 9100:9101
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  logforge-frontend:
    image: madanb13/logforge-frontend:latest
    container_name: ${FRONTEND_SERVICE_CONTAINER_NAME:-logforge-frontend}
    environment:
      VITE_BACKEND_SERVICE_HOST: "http://${BACKEND_SERVICE_CONTAINER_NAME:-logforge-backend}"
      VITE_BACKEND_SERVICE_PORT: "${BACKEND_SERVICE_PORT:-9101}" # Geändert zu 9101
      VITE_EXPOSED_BACKEND_PORT: "${EXPOSED_BACKEND_PORT:-9100}" # Geändert zu 9100
      VITE_NOTIFIER_PORT: "${NOTIFIER_WEB_PORT:-9105}" # Geändert zu 9105
    ports:
      - "${EXPOSED_FRONTEND_PORT:-3000}:${FRONTEND_SERVICE_PORT:-3000}"
    networks:
      - logforge-network
    depends_on:
      - logforge-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  logforge-notifier:
    image: madanb13/logforge-notifier:latest
    container_name: ${NOTIFIER_SERVICE_CONTAINER_NAME:-logforge-notifier}
    ports:
      - "${NOTIFIER_PLAIN_PORT:-9103}:8083" # Geändert zu 9103:8083
      - "${NOTIFIER_WEB_PORT:-9105}:8085" # Geändert zu 9105:8085
    volumes:
      - logforge_notifier_data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - logforge-network
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  logforge-autoupdate:
    image: madanb13/logforge-autoupdate:latest
    container_name: ${AUTOUPDATE_SERVICE_NAME:-logforge-autoupdate}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  logforge-network:
    driver: bridge

volumes:
  logforge_notifier_data:

```

this Work´s :)
